server:
  ip: 127.0.0.1
  port: 50061

devices:
  - name: reactor
    sampling_rate: 2Hz
    driver: generic
    connection:
      port: COM7
      buadRate: 19200

trigger:
  - name: laser
    channel: /dev2/pfi1

logging:
  directory: .output/{:%Y-%m-%d}
  filename: eurotherm-{:%Y-%m-%dT%H-%M-%S}.txt
  format: "%.2f"
  separator: ";"
  rotate_every: 1h
  write_interval: 15s
  columns:
    - deviceName
    - timestamp
    - processValue
    - workingOutput
    - workingSetpoint
# app_logging:
#   version: 1
#   formatters:
#     simple:
#       format: "[%(asctime)s][%(levelname)s][%(thread)s][%(filename)s:%(lineno)d] - %(message)s"
#       datefmt: "%Y-%m-%d %H:%M:%S"
#     rich:
#       format: "[%(thread)s] %(message)s"
#   handlers:
#     textual:
#       class: textual.logging.TextualHandler
#       formatter: rich
#     console:
#       class: rich.logging.RichHandler
#       formatter: rich
#       markup: False
#     file:
#       class: logging.handlers.TimedRotatingFileHandler
#       formatter: simple
#       filename: .eurotherm.log
#       encoding: utf-8
#       when: "d"
#       interval: 1
#   root:
#     level: INFO
#     handlers:
#       - console
#       - file
#       # - textual
#   disable_existing_loggers: false
