# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rservice.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"\r\n\x0bStopRequest\"\x1c\n\x1aStreamProcessValuesRequest\"\xaf\x01\n\rProcessValues\x12\x12\n\ndeviceName\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cprocessValue\x18\x03 \x01(\x01\x12\x15\n\rmeasuredValue\x18\x04 \x01(\x01\x12\x17\n\x0fworkingSetpoint\x18\x05 \x01(\x01\x12\x15\n\rworkingOutput\x18\x06 \x01(\x01\x32\xa0\x01\n\tEurotherm\x12$\n\nStopServer\x12\x0c.StopRequest\x1a\x06.Empty\"\x00\x12%\n\x11ServerHealthCheck\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x46\n\x13StreamProcessValues\x12\x1b.StreamProcessValuesRequest\x1a\x0e.ProcessValues\"\x00\x30\x01\x42\x03\x90\x01\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\220\001\001'
    _globals['_EMPTY']._serialized_start = 50
    _globals['_EMPTY']._serialized_end = 57
    _globals['_STOPREQUEST']._serialized_start = 59
    _globals['_STOPREQUEST']._serialized_end = 72
    _globals['_STREAMPROCESSVALUESREQUEST']._serialized_start = 74
    _globals['_STREAMPROCESSVALUESREQUEST']._serialized_end = 102
    _globals['_PROCESSVALUES']._serialized_start = 105
    _globals['_PROCESSVALUES']._serialized_end = 280
    _globals['_EUROTHERM']._serialized_start = 283
    _globals['_EUROTHERM']._serialized_end = 443
_builder.BuildServices(DESCRIPTOR, 'service_pb2', _globals)
# @@protoc_insertion_point(module_scope)
